import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

// const EduSocialCondensedMedium = localFont({
//   src: "../../public/fonts/EduSocialCondensedMedium.woff2",
//   variable: "--EduSocialCondensedMedium",
//   display: "swap",
// });

const ABCSocialLight = localFont({
  src: "../../public/fonts/ABCSocialLight.woff2",
  variable: "--ABCSocialLight",
  display: "swap",
});

const GTAmericaMonoRegular = localFont({
  src: "../../public/fonts/GTAmericaMonoRegular.woff2",
  variable: "--GTAmericaMonoRegular",
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  variable: "--barlowCondensed",
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${ABCSocialLight.variable} ${GTAmericaMonoRegular.variable} ${barlowCondensed.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
